# Generated by Django 3.0.5 on 2020-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_orderproducts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='orderproducts',
            table='order_products_table',
        ),
    ]
