# Generated by Django 3.0.5 on 2020-04-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200422_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
