# Generated by Django 3.0.5 on 2020-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200430_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='1 Porçao', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
    ]
