# Generated by Django 3.0.5 on 2020-06-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_type_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='endereco'),
            preserve_default=False,
        ),
    ]
