version: '3.5'

services:

  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
